apiVersion: batch/v1
kind: Job
metadata:
  name: init-users
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-users
          image: ghcr.io/cloudnative-pg/postgresql:18.1-system-trixie
          command: ["/bin/sh", "/scripts/init-users.sh"]
          env:
            - name: PGHOST
              value: workshop-pg-cluster-rw
            - name: PGPORT
              value: "5432"
            - name: PGDATABASE
              value: postgres
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: admin-user
                  key: username
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: admin-user
                  key: password
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: init-users-script
            defaultMode: 0755
