apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: pg-proxy
  name: pg-proxy
  namespace: workshop-pg-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pg-proxy
  template:
    metadata:
      labels:
        run: pg-proxy
    spec:
      containers:
        - command:
            - sh
            - -c
            - socat TCP-LISTEN:5432,fork,reuseaddr TCP:workshop-pg-cluster-rw:5432
          image: alpine/socat
          name: pg-proxy
          resources: {}
      dnsPolicy: ClusterFirst
