apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pg-proxy
  name: pg-proxy
  namespace: workshop-pg-cluster
spec:
  containers:
    - args:
        - socat
        - TCP-LISTEN:5432,fork,reuseaddr
        - TCP:workshop-pg-cluster-rw:5432
      image: alpine/socat
      name: pg-proxy
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
