apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: workshop-restore-azure-object-store
spec:
  configuration:
    azureCredentials:
      storageAccount:
        name: azure-storage-account-credentials
        key: account_name
      storageKey:
        name: azure-storage-account-credentials
        key: account_key
    destinationPath: https://cnpgworkshop.blob.core.windows.net/cnpg-workshop-pg-backup/v3
    wal:
      maxParallel: 8
  instanceSidecarConfiguration:
    resources:
      requests:
        memory: 300Mi
        cpu: 100m
      limits:
        memory: 1000Mi
